planner:
  goals:
    p1:
      x: 3.0
      y: 3.0
    p2:
      x: 3.0
      y: -3.0
    p3:
      x: -3.0
      y: 0.0

  speed:
    # min: 0.1
    min: 0.25
    max: 1.
    nominal: 0.25
    dubins: 0.5

  weight:
    u:
      accel: 5.0
      # omega: 500.0
      omega: 250.0
    x:
      # goal: 10.0
      goal: 20.0
      v:
        max: 1000.0
        nominal: 0.0
      lane:
        center: 10.0
        boundary: 100.0
      proximity:
        # p1: 5.0
        # p1: 10.0
        # p2: 5.0
        # p3: 5.0

        p1: 6.0
        p2: 3.0
        p3: 3.0

  proximity:
    min: 2.0
    # min: 1.0
    # min: 1.

  lane:
    # half_width: 0.5
    half_width: 5.
