ilqgame_planner:
  frames:
    fixed: world

  topic:
    traj: /ilq_traj
    state:
      names:
        - /ego
        - /other
      types:
        - EgoState
        - OtherState

  viz:
    traj: /viz/ilq_traj

  replanning_interval: 0.1

  # goals:
  #   p1:
  #     x: 3.0
  #     y: 3.0
  #   p2:
  #     x: 3.0
  #     y: -3.0

  speed:
    min: 1.0
    max: 4.0
    nominal: 3.0
    dubins: 4.0

  weight:
    ego:
      u:
        accel: 5.0
        decel: 1.0
        omega: 50000.0
      x:
        goal: 0.1
        proximity: 10.0
        v:
          max: 1000.0
          nominal: 10.0
        lane:
          center: 50.0
          boundary: 100.0

    other:
      u:
        omega: 50000.0
      x:
        goal: 0.1
        proximity: 10.0

  avoidance_margin:
    ego: 20.0
    other: 20.0

  lane:
    half_width: 10.0

  srv:
    polyline_position: /polyline_position
