ilqgame_planner:
  frames:
    fixed: world

  topic:
    traj: /ilq_traj
    state:
      names:
        - /ego
        - /other
      types:
        - EgoState
        - OtherState

  viz:
    traj: /viz/traj

  replanning_interval: 0.1

  # goals:
  #   p1:
  #     x: 3.0
  #     y: 3.0
  #   p2:
  #     x: 3.0
  #     y: -3.0

  speed:
    min: 1.0
    max: 5.0
    nominal: 4.0
    dubins: 4.0

  weight:
    u:
      accel: 5.0
      omega: 500.0
    x:
      goal: 0.1
      v:
        max: 1000.0
        nominal: 0.1
      lane:
        center: 50.0
        boundary: 100.0
      proximity:
        p1: 10.0
        p2: 10.0

  proximity:
    min: 20.0

  lane:
    half_width: 10.0

  srv:
    polyline_position: /polyline_position
