planner:
  goals:
    p1:
      x: 0.0 
      y: 0.0
    p2:
      x: -748.0
      y: 2322.0 

  speed:
    min: 0.1
    max: 20.0 
    nominal: 15.0 
    dubins: 15.0

  weight:
    u:
      accel: 5.0
      omega: 50.0
    x:
      goal: 10.0
      v:
        max: 100.0
        nominal: 0.0
      lane:
        center: 0.0
        boundary: 10.0
      proximity:
        p1: 1.0
        p2: 1.0

  proximity:
    min: 20.0

  lane:
    half_width: 30.0
